/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hesapmakinesi;


/**
 *
 * @author ASUS PC
 */
public class Makine extends javax.swing.JFrame {

    /**
     * Creates new form Makine
     */
    public Makine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sayi1_Lbl = new javax.swing.JLabel();
        Sayi2_Lbl = new javax.swing.JLabel();
        Sayi1_Txt = new javax.swing.JTextField();
        Sayi2_Txt = new javax.swing.JTextField();
        ToplaBtn = new javax.swing.JButton();
        CikarBtn = new javax.swing.JButton();
        BolBtn = new javax.swing.JButton();
        CarpBtn = new javax.swing.JButton();
        Sonuc_Txt = new javax.swing.JTextField();
        TemizleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sayi1_Lbl.setText("1. Sayı");

        Sayi2_Lbl.setText("2. Sayı");

        Sayi1_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sayi1_TxtActionPerformed(evt);
            }
        });

        Sayi2_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sayi2_TxtActionPerformed(evt);
            }
        });

        ToplaBtn.setText("+");
        ToplaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToplaBtnActionPerformed(evt);
            }
        });

        CikarBtn.setText("-");
        CikarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikarBtnActionPerformed(evt);
            }
        });

        BolBtn.setText("/");
        BolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolBtnActionPerformed(evt);
            }
        });

        CarpBtn.setText("x");
        CarpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarpBtnActionPerformed(evt);
            }
        });

        Sonuc_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sonuc_TxtActionPerformed(evt);
            }
        });

        TemizleBtn.setBackground(new java.awt.Color(204, 255, 255));
        TemizleBtn.setText("Sonuçları Temizle");
        TemizleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Sayi2_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(Sayi1_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Sayi2_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(Sayi1_Txt))
                        .addGap(34, 34, 34)
                        .addComponent(Sonuc_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TemizleBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ToplaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CikarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(CarpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sayi1_Lbl)
                            .addComponent(Sayi1_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sayi2_Lbl)
                            .addComponent(Sayi2_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Sonuc_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToplaBtn)
                    .addComponent(CikarBtn)
                    .addComponent(BolBtn)
                    .addComponent(CarpBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(TemizleBtn)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sayi2_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sayi2_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sayi2_TxtActionPerformed

    private void Sayi1_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sayi1_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sayi1_TxtActionPerformed

    private void Sonuc_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sonuc_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sonuc_TxtActionPerformed

    private void BolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolBtnActionPerformed
     double sayi1,sayi2,toplam;
     String Sayi1,Sayi2;
     
     Sayi1=Sayi1_Txt.getText();
     Sayi2=Sayi2_Txt.getText();
     
     sayi1=Double.parseDouble(Sayi1);
     sayi2=Double.parseDouble(Sayi2);
     
     toplam=sayi1/sayi2;
     Sonuc_Txt.setText(String.valueOf(toplam));
    }//GEN-LAST:event_BolBtnActionPerformed

    private void CarpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarpBtnActionPerformed
     double sayi1,sayi2,toplam;
     String Sayi1,Sayi2;
     
     Sayi1=Sayi1_Txt.getText();
     Sayi2=Sayi2_Txt.getText();
     
     sayi1=Double.parseDouble(Sayi1);
     sayi2=Double.parseDouble(Sayi2);
     
     toplam=sayi1*sayi2;
     Sonuc_Txt.setText(String.valueOf(toplam));
    }//GEN-LAST:event_CarpBtnActionPerformed

    private void ToplaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToplaBtnActionPerformed
     double sayi1,sayi2,toplam;
     String Sayi1,Sayi2;
     
     Sayi1=Sayi1_Txt.getText();
     Sayi2=Sayi2_Txt.getText();
     
     sayi1=Double.parseDouble(Sayi1);
     sayi2=Double.parseDouble(Sayi2);
     
     toplam=sayi1+sayi2;
     Sonuc_Txt.setText(String.valueOf(toplam));
   
    }//GEN-LAST:event_ToplaBtnActionPerformed

    private void TemizleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleBtnActionPerformed
        Sonuc_Txt.setText("");
    }//GEN-LAST:event_TemizleBtnActionPerformed

    private void CikarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikarBtnActionPerformed
     double sayi1,sayi2,toplam;
     String Sayi1,Sayi2;
     
     Sayi1=Sayi1_Txt.getText();
     Sayi2=Sayi2_Txt.getText();
     
     sayi1=Double.parseDouble(Sayi1);
     sayi2=Double.parseDouble(Sayi2);
     
     toplam=sayi1-sayi2;
     Sonuc_Txt.setText(String.valueOf(toplam));
    }//GEN-LAST:event_CikarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Makine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Makine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Makine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Makine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Makine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BolBtn;
    private javax.swing.JButton CarpBtn;
    private javax.swing.JButton CikarBtn;
    private javax.swing.JLabel Sayi1_Lbl;
    private javax.swing.JTextField Sayi1_Txt;
    private javax.swing.JLabel Sayi2_Lbl;
    private javax.swing.JTextField Sayi2_Txt;
    private javax.swing.JTextField Sonuc_Txt;
    private javax.swing.JButton TemizleBtn;
    private javax.swing.JButton ToplaBtn;
    // End of variables declaration//GEN-END:variables
}
